### ISSUE TITLE
Add Template Hub

### ISSUE THREAD

**Issue by WaltDisneyWorld** [Million1156/wlbot#2]
Maybe add a hub template to make it easier for people/.

**Comment by million115** [comment]
Hey! I finally got around to reading your comment,sorry!

What exactly do you mean by "hub template". Do you mean a roblox place where the script is automatically there?
If so,that's kind of not how it works. 
It isn't like MyPod,where it sells it for you. This just verifies that the user is whitelisted,and deletes the model if not. 
For scripting,all you need to do is create a script in the model and paste the code in. (ie: Model>Whitelist>(rest of model parts) )

**Comment by WaltDisneyWorld** [comment]
No, I mean like make some Template ( I can't do UI, but I can help Script it) so that people who want to use this have a "base" for their service. 
Add me on Discord:
`Caleb.#0002`.

**Comment by million115** [comment]
> No, I mean like make some Template ( I can't do UI, but I can help Script it) so that people who want to use this have a "base" for their service.
> Add me on Discord:
> `Caleb.#0002`.

Will do! Accept my friend request.

**Comment by million115** [comment]
Will lock this conversation but keep it for archiving purposes.

The issue was **_not_** resolved since the user meant a different product/service.
:)
